# Surf - Multi-Agent Orchestration Platform

# Run API in development mode with hot reload
dev:
    cd api && uv run uvicorn src.main:app --reload --port 8090

# Launch the DevUI (interactive chat UI for testing agents)
devui:
    cd api && uv run python devui_server.py

# Run API tests
test:
    cd api && uv run pytest

# Run ingestion tests
test-ingestion:
    cd ingestion && uv run pytest

# Lint all Python code
lint:
    cd api && uv run ruff check . && cd ../ingestion && uv run ruff check .

# Type-check all Python code
typecheck:
    cd api && uv run pyright && cd ../ingestion && uv run pyright

# Format all Python code
format:
    cd api && uv run ruff format . && cd ../ingestion && uv run ruff format .

# Deploy minimal Azure resources for local development
# OpenAI is deployed to eastus2 (embedding model); everything else to australiaeast.
# Chat uses Anthropic Claude directly — set ANTHROPIC_API_KEY in .env after setup.
setup-dev:
    #!/usr/bin/env bash
    set -euo pipefail

    RG="rg-surf-dev"
    RG_AI="rg-surf-dev-ai"
    LOCATION="australiaeast"
    LOCATION_AI="eastus2"
    STAMP="surf-dev-$(date +%Y%m%d%H%M%S)"

    SUB_NAME=$(az account show --query name -o tsv)
    SUB_ID=$(az account show --query id -o tsv)
    echo "Active subscription: $SUB_NAME ($SUB_ID)"
    read -rp "Continue with this subscription? [y/N] " CONFIRM
    [[ "$CONFIRM" =~ ^[Yy]$ ]] || { echo "Aborted. Use 'az account set -s <name>' to switch."; exit 1; }

    echo "Getting signed-in user..."
    USER_OID=$(az ad signed-in-user show --query id -o tsv)

    echo "Creating resource groups..."
    az group create --name "$RG"    --location "$LOCATION"    --output none
    az group create --name "$RG_AI" --location "$LOCATION_AI" --output none

    echo "Deploying Azure OpenAI to $RG_AI ($LOCATION_AI)..."
    az deployment group create \
      --resource-group "$RG_AI" \
      --template-file infra/dev-local-openai.bicep \
      --parameters userObjectId="$USER_OID" \
      --name "${STAMP}-ai" \
      --output none

    echo "Deploying remaining infrastructure to $RG ($LOCATION)..."
    az deployment group create \
      --resource-group "$RG" \
      --template-file infra/dev-local.bicep \
      --parameters userObjectId="$USER_OID" \
      --name "$STAMP" \
      --output none

    echo "Fetching deployment outputs..."
    AI_OUTPUTS=$(az deployment group list \
      --resource-group "$RG_AI" \
      --query "sort_by([?starts_with(name,'surf-dev-')],&properties.timestamp)[-1].properties.outputs" \
      --output json)

    OUTPUTS=$(az deployment group list \
      --resource-group "$RG" \
      --query "sort_by([?starts_with(name,'surf-dev-')],&properties.timestamp)[-1].properties.outputs" \
      --output json)

    OPENAI_ENDPOINT=$(echo "$AI_OUTPUTS" | python3 -c "import sys,json; print(json.load(sys.stdin)['openAiEndpoint']['value'])")
    SEARCH_ENDPOINT=$(echo "$OUTPUTS"    | python3 -c "import sys,json; print(json.load(sys.stdin)['searchEndpoint']['value'])")
    COSMOS_ENDPOINT=$(echo "$OUTPUTS"    | python3 -c "import sys,json; print(json.load(sys.stdin)['cosmosEndpoint']['value'])")
    STORAGE_ENDPOINT=$(echo "$OUTPUTS"   | python3 -c "import sys,json; print(json.load(sys.stdin)['storageBlobEndpoint']['value'])")

    echo "Writing .env file..."
    cat > .env <<EOF
    # Generated by 'just setup-dev' — do not commit

    # Anthropic — chat agents (set your API key below)
    ANTHROPIC_API_KEY=
    ANTHROPIC_MODEL_ID=claude-sonnet-4-6

    # Azure OpenAI — embeddings only
    AZURE_OPENAI_ENDPOINT=${OPENAI_ENDPOINT}
    AZURE_OPENAI_API_VERSION=2024-12-01-preview

    # Azure AI Search
    AZURE_SEARCH_ENDPOINT=${SEARCH_ENDPOINT}
    AZURE_SEARCH_INDEX_NAME=surf-index

    # Cosmos DB
    COSMOS_ENDPOINT=${COSMOS_ENDPOINT}
    COSMOS_DATABASE_NAME=surf
    COSMOS_CONTAINER_NAME=conversations

    # Azure Storage
    AZURE_STORAGE_ACCOUNT_URL=${STORAGE_ENDPOINT}

    # Application
    ENVIRONMENT=dev
    LOG_LEVEL=INFO
    EOF

    echo ""
    echo "Done! Your .env has been created."
    echo "IMPORTANT: Set ANTHROPIC_API_KEY in .env before running."
    echo "Run 'just dev' to start the API."

# Run web frontend in development mode
web:
    cd web && npm run dev

# Build web frontend for production
web-build:
    cd web && npm run build

# Lint and typecheck web frontend
web-lint:
    cd web && npm run typecheck

# Install web frontend dependencies
web-install:
    cd web && npm install

# Install mobile app dependencies
mobile-install:
    cd mobile && npm install

# Start mobile app (Expo dev server)
mobile:
    cd mobile && npx expo start

# Start mobile app for iOS simulator
mobile-ios:
    cd mobile && npx expo start --ios

# Start mobile app for Android emulator
mobile-android:
    cd mobile && npx expo start --android

# Deploy API container to Azure Container Apps
api-deploy:
    #!/usr/bin/env bash
    set -euo pipefail
    TAG=$(git rev-parse --short HEAD)
    ACR_SERVER=$(az acr show --name acrsurfdev --resource-group rg-surf-dev --query loginServer -o tsv)
    IMAGE="${ACR_SERVER}/surf-api:${TAG}"
    echo "Logging in to ACR..."
    az acr login --name acrsurfdev
    echo "Building ${IMAGE}..."
    docker build --platform linux/amd64 -t "${IMAGE}" -f api/Dockerfile api/
    echo "Pushing ${IMAGE}..."
    docker push "${IMAGE}"
    echo "Updating Container App..."
    az containerapp update --name ca-api-surf-dev --resource-group rg-surf-dev --image "${IMAGE}" --output none
    echo "API deployed: ${IMAGE}"

# Deploy web frontend to Azure Container Apps (nginx reverse proxy)
web-deploy:
    #!/usr/bin/env bash
    set -euo pipefail
    TAG=$(git rev-parse --short HEAD)
    ACR_SERVER=$(az acr show --name acrsurfdev --resource-group rg-surf-dev --query loginServer -o tsv)
    IMAGE="${ACR_SERVER}/surf-web:${TAG}"
    # Read Entra env vars from web/.env.local (Vite doesn't load .env.local for production builds)
    if [[ -f web/.env.local ]]; then
        export $(grep -E '^VITE_ENTRA_' web/.env.local | xargs)
    fi
    VITE_ENTRA_TENANT_ID="${VITE_ENTRA_TENANT_ID:-$(az account show --query tenantId -o tsv)}"
    echo "Entra Client ID: ${VITE_ENTRA_CLIENT_ID:-not set}"
    echo "Entra Tenant ID: ${VITE_ENTRA_TENANT_ID}"
    echo "Building web SPA..."
    cd web && VITE_ENTRA_CLIENT_ID="${VITE_ENTRA_CLIENT_ID:-}" VITE_ENTRA_TENANT_ID="${VITE_ENTRA_TENANT_ID}" npm run build && cd ..
    echo "Logging in to ACR..."
    az acr login --name acrsurfdev
    echo "Building ${IMAGE}..."
    docker build --platform linux/amd64 -t "${IMAGE}" -f web/Dockerfile web/
    echo "Pushing ${IMAGE}..."
    docker push "${IMAGE}"
    echo "Updating Container App..."
    az containerapp update --name ca-web-surf-dev --resource-group rg-surf-dev --image "${IMAGE}" --output none
    echo "Web deployed: ${IMAGE}"

# Deploy both API and web frontend
deploy: api-deploy web-deploy

# Sync files and pages from SharePoint to blob storage
sync-sharepoint *ARGS:
    cd ingestion && uv run python -m src sync-sharepoint {{ARGS}}

# Create the indexer pipeline (data source, index, skillset, indexer)
setup-indexer *ARGS:
    cd ingestion && uv run python -m scripts.setup_sharepoint_indexer {{ARGS}}

# Trigger an indexer run and optionally wait for completion
run-indexer *ARGS:
    cd ingestion && uv run python -m scripts.run_indexer {{ARGS}}

# Verify Microsoft Graph API access to SharePoint
verify-graph:
    cd ingestion && uv run python -m scripts.verify_graph_access

# Query the SharePoint index and validate results
validate-sharepoint *ARGS:
    cd ingestion && uv run python -m scripts.validate_sharepoint_index {{ARGS}}

# Diagnose the SharePoint indexing pipeline (blobs, index, indexer status)
diagnose-sharepoint *ARGS:
    cd ingestion && uv run python -m scripts.diagnose_sharepoint {{ARGS}}

# Upload a file to SharePoint via Graph API
upload-sharepoint FILE *ARGS:
    cd ingestion && uv run python -m scripts.upload_to_sharepoint "{{FILE}}" {{ARGS}}

# Full end-to-end: sync -> setup indexer -> run indexer -> validate
test-sharepoint-e2e *ARGS:
    cd ingestion && uv run python -m scripts.test_e2e_sharepoint {{ARGS}}

# Delete both dev resource groups and all their resources
teardown-dev:
    #!/usr/bin/env bash
    set -euo pipefail
    SUB_NAME=$(az account show --query name -o tsv)
    echo "⚠ This will DELETE rg-surf-dev and rg-surf-dev-ai in subscription: $SUB_NAME"
    read -rp "Type 'yes' to confirm: " CONFIRM
    [[ "$CONFIRM" == "yes" ]] || { echo "Aborted."; exit 1; }
    az group delete --name rg-surf-dev    --yes --no-wait
    az group delete --name rg-surf-dev-ai --yes --no-wait
    echo "Resource group deletion initiated (runs in background)."
