# Surf - Multi-Agent Orchestration Platform

# Run API in development mode with hot reload
dev:
    cd api && uv run uvicorn src.main:app --reload --port 8090

# Launch the DevUI (interactive chat UI for testing agents)
devui:
    cd api && uv run python devui_server.py

# Run API tests
test:
    cd api && uv run pytest

# Run ingestion tests
test-ingestion:
    cd ingestion && uv run pytest

# Lint all Python code
lint:
    cd api && uv run ruff check . && cd ../ingestion && uv run ruff check .

# Type-check all Python code
typecheck:
    cd api && uv run pyright && cd ../ingestion && uv run pyright

# Format all Python code
format:
    cd api && uv run ruff format . && cd ../ingestion && uv run ruff format .

# Deploy minimal Azure resources for local development
# OpenAI is deployed to eastus2 (embedding model); everything else to australiaeast.
# Chat uses Anthropic Claude directly — set ANTHROPIC_API_KEY in .env after setup.
setup-dev:
    #!/usr/bin/env bash
    set -euo pipefail

    RG="rg-surf-dev"
    RG_AI="rg-surf-dev-ai"
    LOCATION="australiaeast"
    LOCATION_AI="eastus2"
    STAMP="surf-dev-$(date +%Y%m%d%H%M%S)"

    SUB_NAME=$(az account show --query name -o tsv)
    SUB_ID=$(az account show --query id -o tsv)
    echo "Active subscription: $SUB_NAME ($SUB_ID)"
    read -rp "Continue with this subscription? [y/N] " CONFIRM
    [[ "$CONFIRM" =~ ^[Yy]$ ]] || { echo "Aborted. Use 'az account set -s <name>' to switch."; exit 1; }

    echo "Getting signed-in user..."
    USER_OID=$(az ad signed-in-user show --query id -o tsv)

    echo "Creating resource groups..."
    az group create --name "$RG"    --location "$LOCATION"    --output none
    az group create --name "$RG_AI" --location "$LOCATION_AI" --output none

    echo "Deploying Azure OpenAI to $RG_AI ($LOCATION_AI)..."
    az deployment group create \
      --resource-group "$RG_AI" \
      --template-file infra/dev-local-openai.bicep \
      --parameters userObjectId="$USER_OID" \
      --name "${STAMP}-ai" \
      --output none

    echo "Deploying remaining infrastructure to $RG ($LOCATION)..."
    az deployment group create \
      --resource-group "$RG" \
      --template-file infra/dev-local.bicep \
      --parameters userObjectId="$USER_OID" \
      --name "$STAMP" \
      --output none

    echo "Fetching deployment outputs..."
    AI_OUTPUTS=$(az deployment group list \
      --resource-group "$RG_AI" \
      --query "sort_by([?starts_with(name,'surf-dev-')],&properties.timestamp)[-1].properties.outputs" \
      --output json)

    OUTPUTS=$(az deployment group list \
      --resource-group "$RG" \
      --query "sort_by([?starts_with(name,'surf-dev-')],&properties.timestamp)[-1].properties.outputs" \
      --output json)

    OPENAI_ENDPOINT=$(echo "$AI_OUTPUTS" | python3 -c "import sys,json; print(json.load(sys.stdin)['openAiEndpoint']['value'])")
    SEARCH_ENDPOINT=$(echo "$OUTPUTS"    | python3 -c "import sys,json; print(json.load(sys.stdin)['searchEndpoint']['value'])")
    COSMOS_ENDPOINT=$(echo "$OUTPUTS"    | python3 -c "import sys,json; print(json.load(sys.stdin)['cosmosEndpoint']['value'])")
    STORAGE_ENDPOINT=$(echo "$OUTPUTS"   | python3 -c "import sys,json; print(json.load(sys.stdin)['storageBlobEndpoint']['value'])")

    echo "Writing .env file..."
    cat > .env <<EOF
    # Generated by 'just setup-dev' — do not commit

    # Anthropic — chat agents (set your API key below)
    ANTHROPIC_API_KEY=
    ANTHROPIC_MODEL_ID=claude-sonnet-4-6

    # Azure OpenAI — embeddings only
    AZURE_OPENAI_ENDPOINT=${OPENAI_ENDPOINT}
    AZURE_OPENAI_API_VERSION=2024-12-01-preview

    # Azure AI Search
    AZURE_SEARCH_ENDPOINT=${SEARCH_ENDPOINT}
    AZURE_SEARCH_INDEX_NAME=surf-index

    # Cosmos DB
    COSMOS_ENDPOINT=${COSMOS_ENDPOINT}
    COSMOS_DATABASE_NAME=surf
    COSMOS_CONTAINER_NAME=conversations

    # Azure Storage
    AZURE_STORAGE_ACCOUNT_URL=${STORAGE_ENDPOINT}

    # Application
    ENVIRONMENT=dev
    LOG_LEVEL=INFO
    EOF

    echo ""
    echo "Done! Your .env has been created."
    echo "IMPORTANT: Set ANTHROPIC_API_KEY in .env before running."
    echo "Run 'just dev' to start the API."

# Sync files and pages from SharePoint to blob storage
sync-sharepoint *ARGS:
    cd ingestion && uv run python -m src sync-sharepoint {{ARGS}}

# Create the indexer pipeline (data source, index, skillset, indexer)
setup-indexer *ARGS:
    cd ingestion && uv run python scripts/setup_sharepoint_indexer.py {{ARGS}}

# Trigger an indexer run and optionally wait for completion
run-indexer *ARGS:
    cd ingestion && uv run python scripts/run_indexer.py {{ARGS}}

# Verify Microsoft Graph API access to SharePoint
verify-graph:
    cd ingestion && uv run python scripts/verify_graph_access.py

# Query the SharePoint index and validate results
validate-sharepoint *ARGS:
    cd ingestion && uv run python scripts/validate_sharepoint_index.py {{ARGS}}

# Full end-to-end: sync -> setup indexer -> run indexer -> validate
test-sharepoint-e2e: sync-sharepoint setup-indexer (run-indexer "--wait") validate-sharepoint

# Delete both dev resource groups and all their resources
teardown-dev:
    #!/usr/bin/env bash
    set -euo pipefail
    SUB_NAME=$(az account show --query name -o tsv)
    echo "⚠ This will DELETE rg-surf-dev and rg-surf-dev-ai in subscription: $SUB_NAME"
    read -rp "Type 'yes' to confirm: " CONFIRM
    [[ "$CONFIRM" == "yes" ]] || { echo "Aborted."; exit 1; }
    az group delete --name rg-surf-dev    --yes --no-wait
    az group delete --name rg-surf-dev-ai --yes --no-wait
    echo "Resource group deletion initiated (runs in background)."
