#Requires -Version 7.0
<#
.SYNOPSIS
    Deploy minimal Azure resources for local development (Windows equivalent of 'just setup-dev').

.DESCRIPTION
    Creates resource groups, deploys Bicep templates for Azure OpenAI and supporting
    infrastructure, then writes a .env file with the deployment outputs.

.PARAMETER ResourceGroup
    Primary resource group name. Default: rg-surf-dev

.PARAMETER ResourceGroupAI
    AI resource group name (for OpenAI). Default: rg-surf-dev-ai

.PARAMETER Location
    Azure region for primary resources. Default: australiaeast

.PARAMETER LocationAI
    Azure region for OpenAI (embedding model). Default: eastus2
#>
[CmdletBinding()]
param(
    [string]$ResourceGroup = 'rg-surf-dev',
    [string]$ResourceGroupAI = 'rg-surf-dev-ai',
    [string]$Location = 'australiaeast',
    [string]$LocationAI = 'eastus2'
)

$ErrorActionPreference = 'Stop'

$Stamp = "surf-dev-$(Get-Date -Format 'yyyyMMddHHmmss')"

$SubName = az account show --query name -o tsv
$SubId = az account show --query id -o tsv
Write-Host "Active subscription: $SubName ($SubId)"
$Confirm = Read-Host 'Continue with this subscription? [y/N]'
if ($Confirm -notmatch '^[Yy]$') {
    Write-Host "Aborted. Use 'az account set -s <name>' to switch."
    exit 1
}

Write-Host 'Getting signed-in user...'
$UserOid = az ad signed-in-user show --query id -o tsv

Write-Host 'Creating resource groups...'
az group create --name $ResourceGroup   --location $Location   --output none
az group create --name $ResourceGroupAI --location $LocationAI --output none

Write-Host "Deploying Azure OpenAI to $ResourceGroupAI ($LocationAI)..."
az deployment group create `
    --resource-group $ResourceGroupAI `
    --template-file infra/dev-local-openai.bicep `
    --parameters userObjectId=$UserOid `
    --name "$Stamp-ai" `
    --output none

Write-Host "Deploying remaining infrastructure to $ResourceGroup ($Location)..."
az deployment group create `
    --resource-group $ResourceGroup `
    --template-file infra/dev-local.bicep `
    --parameters userObjectId=$UserOid `
    --name $Stamp `
    --output none

Write-Host 'Fetching deployment outputs...'
$AiOutputsJson = az deployment group list `
    --resource-group $ResourceGroupAI `
    --query "sort_by([?starts_with(name,'surf-dev-')],&properties.timestamp)[-1].properties.outputs" `
    --output json
$AiOutputs = $AiOutputsJson | ConvertFrom-Json

$OutputsJson = az deployment group list `
    --resource-group $ResourceGroup `
    --query "sort_by([?starts_with(name,'surf-dev-')],&properties.timestamp)[-1].properties.outputs" `
    --output json
$Outputs = $OutputsJson | ConvertFrom-Json

$OpenAiEndpoint  = $AiOutputs.openAiEndpoint.value
$SearchEndpoint  = $Outputs.searchEndpoint.value
$CosmosEndpoint  = $Outputs.cosmosEndpoint.value
$StorageEndpoint = $Outputs.storageBlobEndpoint.value

Write-Host 'Writing .env file...'
$EnvContent = @"
# Generated by setup-dev.ps1 -- do not commit

# Anthropic -- chat agents (set your API key below)
ANTHROPIC_API_KEY=
ANTHROPIC_MODEL_ID=claude-sonnet-4-6

# Azure OpenAI -- embeddings only
AZURE_OPENAI_ENDPOINT=$OpenAiEndpoint
AZURE_OPENAI_API_VERSION=2024-12-01-preview

# Azure AI Search
AZURE_SEARCH_ENDPOINT=$SearchEndpoint
AZURE_SEARCH_INDEX_NAME=surf-index

# Cosmos DB
COSMOS_ENDPOINT=$CosmosEndpoint
COSMOS_DATABASE_NAME=surf
COSMOS_CONTAINER_NAME=conversations

# Azure Storage
AZURE_STORAGE_ACCOUNT_URL=$StorageEndpoint

# Application
ENVIRONMENT=dev
LOG_LEVEL=INFO
"@

Set-Content -Path .env -Value $EnvContent -Encoding utf8

Write-Host ''
Write-Host 'Done! Your .env has been created.'
Write-Host 'IMPORTANT: Set ANTHROPIC_API_KEY in .env before running.'
Write-Host "Run 'just dev' or 'cd api && uv run uvicorn src.main:app --reload --port 8090' to start the API."
